---
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Infrastructure\Doctrine\EventListener\HashUserPasswordListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
