---
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Infrastructure\Symfony\Messenger\Middleware\:
    resource: '%kernel.project_dir%/src/Infrastructure/Symfony/Messenger/Middleware/**.php'

  Infrastructure\Symfony\Messenger\CommandBus:
    $messageBus: '@command.bus'

  Application\MessageBus\CommandBus:
    alias: Infrastructure\Symfony\Messenger\CommandBus

  Infrastructure\Symfony\Messenger\QueryBus:
    $messageBus: '@query.bus'

  Application\MessageBus\QueryBus:
    alias: Infrastructure\Symfony\Messenger\QueryBus

  Infrastructure\Symfony\Messenger\EventBus:
    $messageBus: '@event.bus'

  Application\MessageBus\EventBus:
    alias: Infrastructure\Symfony\Messenger\EventBus