---
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Domain\UseCase\:
    resource: '%kernel.project_dir%/src/Domain/UseCase/**/Handler.php'
    tags:
      - { name: messenger.message_handler, bus: command.bus }
