---
version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      time: '00:00'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    versioning-strategy: increase

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      time: '00:00'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    versioning-strategy: increase