doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(resolve:MYSQL_HOST)%'
        port: '%env(resolve:MYSQL_PORT)%'
        dbname: '%env(resolve:MYSQL_DATABASE)%'
        user: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'
        server_version: '%env(resolve:MYSQL_VERSION)%'
        charset: utf8mb4
        default_table_options:
           charset: utf8mb4
           collation: utf8mb4_unicode_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/orm'
                prefix: 'App\Entity'
                alias: App
