framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\Dinosaur\Create': async
            'App\Message\Dinosaur\Edit': async
            'App\Message\Dinosaur\Delete': async
