---
version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - '.:/usr/src/app'
    restart: unless-stopped

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/src/app/public
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    restart: unless-stopped

  database:
    image: mysql:8.0.27
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - db-data:/var/lib/mysql:rw
    restart: unless-stopped

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    environment:
      SERVER_NAME: ${MERCURE_SERVER_NAME}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      MERCURE_EXTRA_DIRECTIVES: |
        ${MERCURE_CORS_ALLOW_ORIGIN}
    ports:
      - 81:80

volumes:
  db-data: ~
  mercure_data:
  mercure_config:
