---
version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - '.:/usr/src/app'
    restart: unless-stopped

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/src/app/public
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    restart: unless-stopped

  database:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-RootPass}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
      MYSQL_USER: ${MYSQL_USER:-symfony}
    volumes:
      - db-data:/var/lib/mysql:rw
    restart: unless-stopped

volumes:
  db-data: ~
