app_list_dinosaurs:
  path: /dinosaurs
  controller: App\Controller\DinosaursController::list

app_single_dinosaur:
  path: /dinosaurs/{id}
  controller: App\Controller\DinosaursController::single
  requirements:
    id: \d+

app_create_dinosaur:
  path: /dinosaurs/create
  controller: App\Controller\DinosaursController::create

app_edit_dinosaur:
  path: /dinosaurs/{id}/edit
  controller: App\Controller\DinosaursController::edit
  requirements:
    id: \d+

app_remove_dinosaur:
  path: /dinosaurs/{id}/remove
  controller: App\Controller\DinosaursController::remove
  requirements:
    id: \d+
