---
App\Entity\Dinosaur:
  properties:
    name:
      - NotBlank: ~
      - Length: 
          min: 3
          max: 255
          minMessage: 'The name must contain at least 3 characters'
          maxMessage: 'The name must contain at most 255 characters'
    gender:
      - NotBlank: ~
      - Length: 
          min: 3
          max: 255
          minMessage: 'The gender must contain at least 3 characters'
          maxMessage: 'The gender must contain at most 255 characters'
    species:
      - NotBlank: ~
    age:
      - NotBlank: ~
      - Positive: 
          message: 'The age must be greater than 0'
