---
parameters:
  env(MYSQL_HOST): '%env(resolve:MYSQL_HOST)%'
  env(MYSQL_DATABASE): '%env(resolve:MYSQL_DATABASE)%'
  env(MYSQL_USER): '%env(resolve:MYSQL_USER)%'
  env(MYSQL_PASSWORD): '%env(resolve:MYSQL_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\:
        resource: '../src/Application/'
        exclude:
          - '../src/Application/DomainEventsHandler/'

    Infrastructure\Doctrine\DataFixtures\:
        resource: '../src/Infrastructure/Doctrine/DataFixtures/**.php'
