name: Automatic rebase

on:
    workflow_dispatch: ~
    push:
        branches:
            - master

jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: gh test
              run: |
                  gh pr list --label Module --limit 50
                  gh repo clone ${{ github.repository }} -- --branch my-beautiful-branch
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
